# Generated by Django 5.2.1 on 2025-06-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_myuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
